"""Initial migration with favorite_food and spice_level

Revision ID: 98dfd01592f3
Revises: 
Create Date: 2024-11-01 16:40:03.377161

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '98dfd01592f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rcp_set', schema=None) as batch_op:
        batch_op.alter_column('rcp_nm',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.drop_column('manual11')
        batch_op.drop_column('manual_img20')
        batch_op.drop_column('info_na')
        batch_op.drop_column('manual05')
        batch_op.drop_column('manual_img04')
        batch_op.drop_column('manual20')
        batch_op.drop_column('manual_img17')
        batch_op.drop_column('info_car')
        batch_op.drop_column('manual14')
        batch_op.drop_column('rcp_pat2')
        batch_op.drop_column('manual_img19')
        batch_op.drop_column('manual_img05')
        batch_op.drop_column('manual09')
        batch_op.drop_column('manual_img15')
        batch_op.drop_column('manual_img08')
        batch_op.drop_column('manual_img13')
        batch_op.drop_column('manual_img14')
        batch_op.drop_column('manual10')
        batch_op.drop_column('manual16')
        batch_op.drop_column('info_wgt')
        batch_op.drop_column('manual13')
        batch_op.drop_column('manual18')
        batch_op.drop_column('manual08')
        batch_op.drop_column('rcp_parts_dtls')
        batch_op.drop_column('rcp_na_tip')
        batch_op.drop_column('manual04')
        batch_op.drop_column('manual_img06')
        batch_op.drop_column('manual03')
        batch_op.drop_column('manual_img12')
        batch_op.drop_column('manual_img18')
        batch_op.drop_column('manual_img03')
        batch_op.drop_column('manual17')
        batch_op.drop_column('manual06')
        batch_op.drop_column('manual12')
        batch_op.drop_column('manual_img09')
        batch_op.drop_column('manual_img10')
        batch_op.drop_column('manual07')
        batch_op.drop_column('manual01')
        batch_op.drop_column('manual15')
        batch_op.drop_column('info_eng')
        batch_op.drop_column('hash_tag')
        batch_op.drop_column('manual_img01')
        batch_op.drop_column('manual_img16')
        batch_op.drop_column('rcp_seq')
        batch_op.drop_column('att_file_no_mk')
        batch_op.drop_column('manual02')
        batch_op.drop_column('info_fat')
        batch_op.drop_column('info_pro')
        batch_op.drop_column('manual_img11')
        batch_op.drop_column('manual19')
        batch_op.drop_column('rcp_way2')
        batch_op.drop_column('manual_img07')
        batch_op.drop_column('manual_img02')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_food', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('spice_level', sa.Integer(), nullable=True))
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('spice_level')
        batch_op.drop_column('favorite_food')

    with op.batch_alter_table('rcp_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manual_img02', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual_img07', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('rcp_way2', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual19', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual_img11', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('info_pro', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('info_fat', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual02', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('att_file_no_mk', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('rcp_seq', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual_img16', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual_img01', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('hash_tag', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('info_eng', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual15', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual01', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual07', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual_img10', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual_img09', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual12', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual06', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual17', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual_img03', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual_img18', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual_img12', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual03', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual_img06', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual04', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('rcp_na_tip', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('rcp_parts_dtls', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual08', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual18', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual13', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('info_wgt', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual16', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual10', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual_img14', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual_img13', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual_img08', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual_img15', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual09', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual_img05', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual_img19', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('rcp_pat2', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual14', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('info_car', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual_img17', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual20', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual_img04', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual05', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('info_na', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual_img20', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manual11', mysql.TEXT(), nullable=True))
        batch_op.alter_column('rcp_nm',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
