"""Add rcp_pat2 column as Text to Recipe model

Revision ID: c9546581a410
Revises: 98dfd01592f3
Create Date: 2024-11-03 14:37:21.886282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9546581a410'
down_revision = '98dfd01592f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rcp_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rcp_pat2', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rcp_set', schema=None) as batch_op:
        batch_op.drop_column('rcp_pat2')

    # ### end Alembic commands ###
