"""Fix conversation table and fields

Revision ID: e3a1a063524a
Revises: 17c90be34459
Create Date: 2024-11-05 11:30:18.560205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e3a1a063524a'
down_revision = '17c90be34459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.alter_column('summary_text',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.alter_column('summary_text',
               existing_type=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
