"""Update Recipe model with all fields

Revision ID: fb9051b0d41a
Revises: c9546581a410
Create Date: 2024-11-04 21:38:23.761872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb9051b0d41a'
down_revision = 'c9546581a410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rcp_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rcp_seq', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rcp_way2', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('info_wgt', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('info_eng', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('info_car', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('info_pro', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('info_fat', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('info_na', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('hash_tag', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('att_file_no_mk', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rcp_parts_dtls', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rcp_na_tip', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual01', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual_img01', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual02', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual_img02', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual03', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual_img03', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual04', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual_img04', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual05', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual_img05', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual06', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual_img06', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual07', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual_img07', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual08', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual_img08', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual09', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual_img09', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual10', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual_img10', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual11', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual_img11', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual12', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual_img12', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual13', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual_img13', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual14', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual_img14', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual15', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual_img15', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual16', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual_img16', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual17', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual_img17', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual18', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual_img18', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual19', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual_img19', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual20', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual_img20', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rcp_set', schema=None) as batch_op:
        batch_op.drop_column('manual_img20')
        batch_op.drop_column('manual20')
        batch_op.drop_column('manual_img19')
        batch_op.drop_column('manual19')
        batch_op.drop_column('manual_img18')
        batch_op.drop_column('manual18')
        batch_op.drop_column('manual_img17')
        batch_op.drop_column('manual17')
        batch_op.drop_column('manual_img16')
        batch_op.drop_column('manual16')
        batch_op.drop_column('manual_img15')
        batch_op.drop_column('manual15')
        batch_op.drop_column('manual_img14')
        batch_op.drop_column('manual14')
        batch_op.drop_column('manual_img13')
        batch_op.drop_column('manual13')
        batch_op.drop_column('manual_img12')
        batch_op.drop_column('manual12')
        batch_op.drop_column('manual_img11')
        batch_op.drop_column('manual11')
        batch_op.drop_column('manual_img10')
        batch_op.drop_column('manual10')
        batch_op.drop_column('manual_img09')
        batch_op.drop_column('manual09')
        batch_op.drop_column('manual_img08')
        batch_op.drop_column('manual08')
        batch_op.drop_column('manual_img07')
        batch_op.drop_column('manual07')
        batch_op.drop_column('manual_img06')
        batch_op.drop_column('manual06')
        batch_op.drop_column('manual_img05')
        batch_op.drop_column('manual05')
        batch_op.drop_column('manual_img04')
        batch_op.drop_column('manual04')
        batch_op.drop_column('manual_img03')
        batch_op.drop_column('manual03')
        batch_op.drop_column('manual_img02')
        batch_op.drop_column('manual02')
        batch_op.drop_column('manual_img01')
        batch_op.drop_column('manual01')
        batch_op.drop_column('rcp_na_tip')
        batch_op.drop_column('rcp_parts_dtls')
        batch_op.drop_column('att_file_no_mk')
        batch_op.drop_column('hash_tag')
        batch_op.drop_column('info_na')
        batch_op.drop_column('info_fat')
        batch_op.drop_column('info_pro')
        batch_op.drop_column('info_car')
        batch_op.drop_column('info_eng')
        batch_op.drop_column('info_wgt')
        batch_op.drop_column('rcp_way2')
        batch_op.drop_column('rcp_seq')

    # ### end Alembic commands ###
